on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.REQUIRE_FOCUSED_REVIEW: true
          CONFIG.REQUIRE_SCORE_REVIEW: true
          CONFIG.INLINE_CODE_COMMENTS: true
          CONFIG.ASK_AND_REFLECT: true
          CONFIG.PUBLISH_DESCRIPTION_AS_COMMENT: true
          CONFIG.ADD_ORIGINAL_USER_DESCRIPTION: true
          CONFIG.KEEP_ORIGINAL_USER_TITLE: true
          CONFIG.PUSH_CHANGELOG_CHANGES: true
