name: Prettier Check

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm ci

      - name: Check Formatting
        run: npx prettier --check .
